# management.security.enabled=false
# management.endpoints.env.enabled=true
# management.endpoints.web.exposure.include=*

# management:
#   endpoint:
#     env:
#       enabled: true
#     refresh:
#       enabled: true
#   endpoints:
#     web:
#       exposure:
#         include: env
management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
